post http://localhost:3000/api/v1/users/signup
content-type: application/json

{
    "@type": "Person2",
    "name": "test2",
    "email": "test2@test.com",
    "password": "test1234",
    "passwordConfirm": "test1234"
}

###

post http://localhost:3000/api/v1/users/login
content-type: application/json

{
	"email": "test@test.com",
	"password": "test1234"
}


###
post http://localhost:3000/api/v1/community/
content-type: application/json

{
    "isPublic": true,
    "name": "Hisarüstü Cafeleri",
    "description": "Hisarüstü'nün en iyi cafeleri burada",
    "tags": ["cafe", "food", "hisarüstü"]
}


###
post http://localhost:3000/api/v1/community/60be2f36b9901705f47a09ac/postTypes
content-type: application/json

{
    "title": "Cafe",
    "description": "Nice cafes",
    "tags": ["cafe", "coffee", "drink"],
    "communityDataTypeFields": [
        {
            "@type":"cdt:communityDataTypeField",
            "fieldName": "Cafe Name",
            "fieldIsRequired": true,
            "fieldIsEditable": false,
            "fieldType": "Text"
        },
        {
            "@type":"cdt:communityDataTypeField",
            "fieldName": "Location",
            "fieldIsRequired": true,
            "fieldIsEditable": false,
            "fieldType": "Geolocation"
        }
    ]
}

###

post http://localhost:3000/api/v1/community/60be2f36b9901705f47a09ac/postTypes/60be2fedb9901705f47a09ad/posts
content-type: application/json

{
    "title": "Best Place for tahin sufle!",
    "description": "Desert for your soul!",
    "tags": ["breakfast", "cafe", "sufle", "tahin"],
    "postFields": [
        {
           "label": "Cafe Name",
           "value": "Daktilo"
        },
        {   
            "label": "Location",
            "value": {
                "latitude": 41.086319,
                "longitude": 29.046067
            }
        }
    ]
}


###
get http://localhost:3000/api/v1/community/60bced4504bcfe30182f0202/postTypes
content-type: application/json


###
get http://localhost:3000/api/v1/community/60bd052c68e4902d601759f7/posts
content-type: application/json




###
get http://localhost:3000/api/v1/users/usersByName/?name=test
content-type: application/json
